version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      mui-major:
        applies-to: version-updates
        patterns:
          - "@mui/*"
        update-types:
          - "major"
      react-major:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "major"
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
